# Generated by Django 3.1.3 on 2020-11-25 05:59

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Alquiler',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
            ],
        ),
        migrations.CreateModel(
            name='Evento',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titulo', models.CharField(max_length=100)),
                ('fecha', models.DateTimeField(blank=True)),
                ('cliente', models.CharField(max_length=80)),
                ('telefono', models.CharField(max_length=8)),
                ('direccion', models.CharField(max_length=120)),
                ('referencia', models.CharField(max_length=180)),
                ('estado', models.CharField(blank=True, max_length=10, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Material',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=100)),
                ('costo', models.DecimalField(decimal_places=2, max_digits=8)),
                ('eventos', models.ManyToManyField(through='alquiler.Alquiler', to='alquiler.Evento')),
            ],
        ),
        migrations.AddField(
            model_name='alquiler',
            name='evento',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='alquiler.evento'),
        ),
        migrations.AddField(
            model_name='alquiler',
            name='material',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='alquiler.material'),
        ),
    ]
