# Generated by Django 3.1.3 on 2020-11-25 07:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('alquiler', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='material',
            name='eventos',
        ),
        migrations.AddField(
            model_name='evento',
            name='materials',
            field=models.ManyToManyField(through='alquiler.Alquiler', to='alquiler.Material'),
        ),
    ]
